-- NovaCell 회원·상품 이용권 데이터베이스
-- Supabase SQL Editor에서 전체를 한 번 실행합니다.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  full_name text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  code text primary key,
  name_ko text not null,
  name_en text not null,
  price_krw integer not null check (price_krw >= 0),
  price_usd integer not null check (price_usd >= 0),
  duration_days integer not null default 365 check (duration_days > 0),
  active boolean not null default true
);

create table if not exists public.entitlements (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  product_code text not null references public.products(code),
  status text not null default 'active' check (status in ('active','expired','revoked','refunded')),
  starts_at timestamptz not null default now(),
  expires_at timestamptz,
  source text not null default 'admin_test',
  granted_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, product_code)
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

insert into public.products (code,name_ko,name_en,price_krw,price_usd,duration_days)
values
  ('reflex_therapy_1y','NovaCell Reflex Therapy Guide 1년 이용권','NovaCell Reflex Therapy Guide 1-Year Pass',99000,100,365),
  ('healing_points_1y','NovaCell Healing Points 1년 이용권','NovaCell Healing Points 1-Year Pass',330000,300,365)
on conflict (code) do update set
  name_ko=excluded.name_ko,name_en=excluded.name_en,price_krw=excluded.price_krw,
  price_usd=excluded.price_usd,duration_days=excluded.duration_days,active=true;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id,email,full_name)
  values (new.id,lower(coalesce(new.email,'')),coalesce(new.raw_user_meta_data->>'full_name',''))
  on conflict (id) do update set email=excluded.email,full_name=excluded.full_name,updated_at=now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert or update of email,raw_user_meta_data on auth.users
for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.entitlements enable row level security;
alter table public.admin_users enable row level security;

grant usage on schema public to anon, authenticated;
grant select on public.products to anon, authenticated;
grant select on public.profiles, public.entitlements, public.admin_users to authenticated;

drop policy if exists "members read own profile" on public.profiles;
create policy "members read own profile" on public.profiles for select using (auth.uid() = id);
drop policy if exists "public reads active products" on public.products;
create policy "public reads active products" on public.products for select using (active = true);
drop policy if exists "members read own entitlements" on public.entitlements;
create policy "members read own entitlements" on public.entitlements for select using (auth.uid() = user_id);
drop policy if exists "admins read own admin row" on public.admin_users;
create policy "admins read own admin row" on public.admin_users for select using (auth.uid() = user_id);

-- 기존 회원이 있는 상태에서 이 스키마를 설치한 경우 프로필을 채웁니다.
insert into public.profiles (id,email,full_name)
select id,lower(coalesce(email,'')),coalesce(raw_user_meta_data->>'full_name','') from auth.users
on conflict (id) do nothing;

-- 박 교수님 계정으로 회원가입을 완료한 뒤 아래 이메일을 실제 관리자 이메일로 바꾸어 실행하세요.
-- insert into public.admin_users (user_id)
-- select id from auth.users where lower(email)=lower('YOUR_ADMIN_EMAIL@example.com')
-- on conflict (user_id) do nothing;
