const CIRCUITS=[
 {id:'lung',order:1,code:'LU',name:'폐 회로',en:'Lung (LU) Circuit',page:204,image:'assets/circuits/lung.webp',route:'흉부 외측 → 상지 내측 전면 → 엄지 내측',check:'LU 8',supply:'LU 7',uses:'천식, 폐결핵, 기침, 편도선, 감기, 갱년기 장애, 어깨관절 통증, 목구멍이나 기관지에 생긴 질병 등의 질환에 적용합니다.'},
 {id:'large-intestine',order:2,code:'LI',name:'대장 회로',en:'Large Intestine (LI) Circuit',page:205,image:'assets/circuits/large-intestine.webp',route:'식지 내측 → 상지 외측 전면 → 인중에서 교차 → 코 양측',check:'LI 5',supply:'LI 5',uses:'편도선, 두통, 코병, 눈병, 인후통, 어깨결림, 비염, 후각마비, 축농증, 고혈압, 피부병 등의 질환에 적용합니다.'},
 {id:'heart',order:3,code:'HT',name:'심장 회로',en:'Heart (HT) Circuit',page:206,image:'assets/circuits/heart.webp',route:'겨드랑이 → 상지 내측 후면 → 수5지 내측',check:'HT 7',supply:'HT 5',uses:'심장병, 이명, 눈의 충혈, 천식, 피로회복, 심한 어깨 결림, 호흡장애, 팔꿈치통증, 신경쇠약, 고혈압 등의 질환에 적용합니다.'},
 {id:'small-intestine',order:4,code:'SI',name:'소장 회로',en:'Small Intestine (SI) Circuit',page:207,image:'assets/circuits/small-intestine.webp',route:'수5지 외측 → 상지 외측 후면 → 견갑부 → 목 → 귀 앞',check:'SI 5',supply:'SI 7',uses:'어깨 결림, 신경통, 오십견, 이명, 혈압항진, 척골신경통, 변비, 목이 뻣뻣해지는 증상, 안면신경마비 등의 질환에 적용합니다.'},
 {id:'spleen',order:5,code:'SP',name:'비장 회로',en:'Spleen/Pancreas (SP) Circuit',page:208,image:'assets/circuits/spleen.webp',route:'족무지 내측 → 경골 내측 후면 → 대퇴 내측 전면 → 흉복부 → 겨드랑이',check:'SP 5',supply:'SP 4',uses:'뇌의 전두엽, 황반, 각막, 눈꺼풀, 피부, 림프, 부신, 식중독, 신장, 당뇨병, 심한 졸음, 장 질환, 변비, 늑간 신경통, 천식, 유아천식 등의 질환에 적용합니다.'},
 {id:'stomach',order:6,code:'ST',name:'위장 회로',en:'Stomach (ST) Circuit',page:209,image:'assets/circuits/stomach.webp',route:'눈 아래 → 얼굴 → 흉복부 → 하지 외측 전면 → 족2지 외측',check:'ST 42',supply:'ST 40',uses:'치통, 안면신경마비, 위궤양, 장질환, 신장병, 변비, 대하증, 월경불순, 복부의 냉증, 만성 위질환, 구토증, 위통, 뇌의 전두엽, 황반, 각막, 눈꺼풀 등의 질환에 적용합니다.'},
 {id:'kidney',order:7,code:'KI',name:'신장 회로',en:'Kidney (KI) Circuit',page:210,image:'assets/circuits/kidney.webp',route:'발바닥 중심 → 하지 내측 후면 → 흉복부 전면',check:'KI 5',supply:'KI 4',uses:'신장병, 약물중독, 모든 만성병, 당뇨병, 복막염, 호흡기 질환, 장 질환, 방광 질환, 머리가 무거울 때, 생식기 질환, 신경쇠약 등의 질환에 적용합니다.'},
 {id:'bladder',order:8,code:'BL',name:'방광 회로',en:'Bladder (BL) Circuit',page:211,image:'assets/circuits/bladder.webp',route:'눈 내측면 → 두부·경부 후면 → 요배부 → 하지 외측 후면 → 족5지 외측',check:'BL 66',supply:'BL 58',uses:'이명, 현기증, 불면증, 축농증, 두통, 눈병, 감기, 인후통, 편도선염, 고혈압, 어깨결림, 협심증, 폐렴, 천식, 방광 질환, 대장 질환, 변비, 요통 등의 질환에 적용합니다.'},
 {id:'liver',order:9,code:'LV',name:'간 회로',en:'Liver (LV) Circuit',page:212,image:'assets/circuits/liver.webp',route:'족무지 외측 → 발등 내측 전면 → 하퇴·대퇴 내측 → 외음부를 돌아 → 늑골 아래',check:'LV 1',supply:'LV 5, LV 14',uses:'녹내장, 시신경, 망막, 근육 이완이나 경직, 경련, 부인과 질환, 신장 질환, 빈뇨, 간장 질환, 담석증, 늑막염, 비장 질환, 만성 위장 질환 등의 질환에 적용합니다.'},
 {id:'gallbladder',order:10,code:'GB',name:'담낭 회로',en:'Gall Bladder (GB) Circuit',page:213,image:'assets/circuits/gallbladder.webp',route:'구외각 → 두부를 거쳐 → 목·늑골·요부 → 하지 외측 정중면 → 족4지 외측',check:'GB 48',supply:'GB 37',uses:'귀, 뇌일혈, 두통, 편두통, 콧병, 담낭 질환, 황달, 늑간 신경통, 위의 질환, 신장병, 방광 질환, 안면 신경통, 모든 냉기에 의한 질병 등의 질환에 적용합니다.'},
 {id:'pericardium',order:11,code:'PC',name:'심포 회로',en:'Parasympathetic (PC) Circuit',page:214,image:'assets/circuits/pericardium.webp',route:'가슴 → 어깨 → 팔 안쪽 중앙 → 손바닥 → 중지 끝',check:'PC 7',supply:'PC 8',uses:'횡격막 위에 있는 모든 병, 심장병, 폐결핵, 천식, 신경 쇠약, 늑막염, 피로회복 등의 질환에 적용합니다.'},
 {id:'triple-burner',order:12,code:'TB',name:'삼초 회로',en:'Sympathetic/Triple Burner (TB) Circuit',page:215,image:'assets/circuits/triple-burner.webp',route:'수4지 외측 → 상지 외측 정중면 → 어깨·목 → 귀를 돌아 → 견외측',check:'TB 4',supply:'TB 5',uses:'모든 부인병, 갱년기 장애, 변비, 소장의 질환, 맹장, 난청, 이명, 두통, 출혈성 질환, 월경 이상, 피로 회복, 중이염, 치통, 어깨 결림, 상지 신경통, 편두통, 눈병 등의 질환에 적용합니다.'},
 {id:'conception-vessel',order:13,code:'CV',name:'임맥 회로',en:'Conception Vessel (CV) Circuit',page:216,image:'assets/circuits/conception-vessel.webp',route:'회음 → 음부·복부 → 몸의 앞 정중선 → 목구멍 → 입술을 돌아 → 뺨 → 눈 속',check:'책에 별도 표기 없음',supply:'책에 별도 표기 없음',usesTitle:'책에 기재된 설명',uses:'임맥(CV)은 몸의 앞 정중선에 분포되어 있습니다. 회음에서 시작하여 음부와 뱃속을 지나 몸의 앞 정중선을 따라 곧바로 목구멍에까지 가서 입술을 돈 다음 뺨을 지나 눈 속으로 들어갑니다. 온몸의 마이너스 에너지를 조절합니다.'},
 {id:'governor-vessel',order:14,code:'GV',name:'독맥 회로',en:'Governor Vessel (GV) Circuit',page:217,image:'assets/circuits/governor-vessel.webp',route:'미골 아래 → 척추 속 → 뇌 속 → 정수리 → 이마·콧마루 → 윗잇몸 속',check:'책에 별도 표기 없음',supply:'책에 별도 표기 없음',usesTitle:'책에 기재된 설명',uses:'독맥(GV)은 미골 아래에서 시작하여 척추 속을 따라 올라가다가 뇌 속으로 들어가서 정수리로 나온 다음 이마와 콧마루를 지나 윗잇몸 속으로 들어갑니다. 독맥(GV)은 온몸의 플러스 에너지를 통솔하며, 뇌·척추·회음부와 연계됩니다.'}
];

const $=id=>document.getElementById(id);let selected=0,query='';
const escapeHTML=v=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function matches(c){const hay=[c.name,c.en,c.code,c.route,c.check,c.supply,c.uses].join(' ').toLocaleLowerCase('ko-KR');return hay.includes(query.toLocaleLowerCase('ko-KR'));}
function renderList(){const list=CIRCUITS.filter(matches);$('circuit-list').innerHTML=list.length?list.map(c=>`<button class="circuit-item ${CIRCUITS[selected].id===c.id?'active':''}" type="button" role="option" aria-selected="${CIRCUITS[selected].id===c.id}" data-id="${c.id}"><span class="circuit-number">${String(c.order).padStart(2,'0')}</span><span class="circuit-name"><strong>${escapeHTML(c.name)}</strong><small>${escapeHTML(c.en)}</small></span><span class="circuit-code">${c.code}</span></button>`).join(''):'<p class="empty-list">검색 결과가 없습니다.</p>';}
function renderDetail(){const c=CIRCUITS[selected];$('circuit-sequence').textContent=`${String(c.order).padStart(2,'0')} / ${CIRCUITS.length}`;$('circuit-title').textContent=c.name;$('circuit-title-en').textContent=c.en;$('source-page').textContent=`책 ${c.page}쪽`;$('circuit-route').textContent=c.route;$('circuit-check').textContent=c.check;$('circuit-supply').textContent=c.supply;$('circuit-check').classList.toggle('not-listed',c.check==='책에 별도 표기 없음');$('circuit-supply').classList.toggle('not-listed',c.supply==='책에 별도 표기 없음');$('circuit-uses-title').textContent=c.usesTitle||'책에 기재된 적용 질환';$('circuit-uses').textContent=c.uses;const img=$('circuit-image');img.src=c.image;img.alt=`${c.name}의 인체 회로 도해`;$('circuit-caption').textContent=`『노바셀 통치 요법』 ${c.page}쪽 관련 도해 · ${c.name}${c.check==='책에 별도 표기 없음'?' · 체크·공급점 별도 표기 없음':` · 체크 ${c.check} · 공급 ${c.supply}`}`;renderList();history.replaceState(null,'','#'+c.id);}
function revealSelectedCircuit(){const detail=document.querySelector('.circuit-detail');if(!detail)return;if(matchMedia('(max-width: 920px)').matches){requestAnimationFrame(()=>detail.scrollIntoView({top:0,behavior:'smooth',block:'start'}));}else{detail.scrollTo({top:0,behavior:'smooth'});}}
function selectById(id,{reveal=true}={}){const i=CIRCUITS.findIndex(c=>c.id===id);if(i<0)return;selected=i;renderDetail();if(reveal)revealSelectedCircuit();}
$('circuit-list').addEventListener('click',event=>{const button=event.target.closest('.circuit-item');if(!button)return;event.preventDefault();selectById(button.dataset.id);});
$('circuit-search').addEventListener('input',e=>{query=e.target.value.trim();renderList();});
$('previous-circuit').onclick=()=>{selected=(selected-1+CIRCUITS.length)%CIRCUITS.length;renderDetail();revealSelectedCircuit();};
$('next-circuit').onclick=()=>{selected=(selected+1)%CIRCUITS.length;renderDetail();revealSelectedCircuit();};
document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea'))return;if(e.key==='ArrowLeft')$('previous-circuit').click();if(e.key==='ArrowRight')$('next-circuit').click();});
const initial=location.hash.slice(1);if(CIRCUITS.some(c=>c.id===initial))selected=CIRCUITS.findIndex(c=>c.id===initial);renderDetail();
