const maps=[
 {id:"right_sole",icon:"🦶",title:"오른발 발바닥",en:"Right sole",side:"RIGHT · FOOT",image:"foot-sole-map.webp",page:27},
 {id:"left_sole",icon:"🦶",title:"왼발 발바닥",en:"Left sole",side:"LEFT · FOOT",image:"foot-sole-map.webp",page:27},
 {id:"right_top",icon:"🦶",title:"오른발 발등",en:"Right foot top",side:"RIGHT · FOOT",image:"foot-top-map.webp",page:28},
 {id:"left_top",icon:"🦶",title:"왼발 발등",en:"Left foot top",side:"LEFT · FOOT",image:"foot-top-map.webp",page:28},
 {id:"right_palm",icon:"🖐️",title:"오른손 손바닥",en:"Right palm",side:"RIGHT · HAND",image:"hand-palm-map.webp",page:31},
 {id:"left_palm",icon:"🖐️",title:"왼손 손바닥",en:"Left palm",side:"LEFT · HAND",image:"hand-palm-map.webp",page:31},
 {id:"right_back",icon:"🤚",title:"오른손 손등",en:"Right hand back",side:"RIGHT · HAND",image:"hand-back-map.webp",page:32},
 {id:"left_back",icon:"🤚",title:"왼손 손등",en:"Left hand back",side:"LEFT · HAND",image:"hand-back-map.webp",page:32}
];
const key="novacell_reflex_therapy_v1";
const state={mode:"self",lang:"ko",voice:true,sound:true,view:"map",mapId:"right_sole",zoom:1,panX:0,panY:0,points:[],records:[],academy:{lessons:[],quizBest:0,practiceBest:0,attempts:0},academyCourse:"urinary",academyTab:"learn",lesson:0,quiz:0,quizScore:0,practiceTimer:null,practiceActive:false,practiceTime:60,practiceStep:0,practiceScore:0,activeProgram:null,selectedSystem:null,sessionMap:"foot",sessionZoom:1,sessionPanX:0,sessionPanY:0,sessionFit:true,step:0,time:20,defaultDuration:20,sessionDurations:[],timer:null,pendingPoint:null,selectedPoint:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const uiText={
 ko:{selfMode:"자가관리",proMode:"전문가",safety:"안전 안내",navMap:"1. 반사 지도",navPrograms:"2. 프로그램",navSession:"3. 치료 세션",navRecords:"4. 기록·백업",footMap:"🦶 발 지도",handMap:"🖐️ 손 지도",fitAll:"전체 보기",nextPoint:"다음 포인트",finishRecord:"완료·기록",start:"시작",pause:"일시정지",restart:"다시 시작",voiceOn:"🔊 음성",voiceOff:"🔇 음성",soundOn:"♪ 알림",soundOff:"♪ 무음",full:"전체",current:"현재",footWork:"발 작업점 지도",handWork:"손 작업점 지도",location:"위치",method:"방법",page:"교재",both:"양쪽",gentle:"편안한 3–4/10",veryLight:"매우 가볍게 1–2/10",repeat:"좌우 각 1–2회",frequent:"짧게 자주 반복",seconds:"초",completed:"현재 포인트가 완료되었습니다.",last:"마지막 포인트입니다.",chooseProgram:"프로그램을 먼저 선택하세요.",sessionSaved:"치료 기록을 저장했습니다."},
 en:{selfMode:"Self-care",proMode:"Professional",safety:"Safety",navMap:"1. Reflex Maps",navPrograms:"2. Programs",navSession:"3. Treatment Session",navRecords:"4. Records & Backup",footMap:"🦶 Foot map",handMap:"🖐️ Hand map",fitAll:"Fit all",nextPoint:"Next point",finishRecord:"Finish & save",start:"Start",pause:"Pause",restart:"Restart",voiceOn:"🔊 Voice",voiceOff:"🔇 Voice",soundOn:"♪ Sound",soundOff:"♪ Muted",full:"Fit",current:"Current",footWork:"Foot reflex map",handWork:"Hand reflex map",location:"Location",method:"Method",page:"Textbook",both:"Both sides",gentle:"Comfortable 3–4/10",veryLight:"Very light 1–2/10",repeat:"1–2 times each side",frequent:"Repeat briefly and often",seconds:"sec",completed:"The current point is complete.",last:"This is the last point.",chooseProgram:"Please select a program first.",sessionSaved:"Treatment record saved."}
};
Object.assign(uiText.ko,{navAcademy:"5. Academy",academyTitle:"Academy 교육센터",academyIntro:"교재 내용을 학습하고, 그림 퀴즈와 실기평가로 익혀 보세요.",courseProgress:"과정 진도",academyLearn:"학습하기",academyQuiz:"퀴즈",academyPractice:"실기평가",academyProgress:"학습 진도",urinaryCourse:"비뇨계 반사요법",urinaryCourseIntro:"신장·방광·부신 반사구의 위치와 작업 순서를 학습합니다.",quizTitle:"그림에서 반사구 찾기",practiceTitle:"비뇨계 실기평가"});
Object.assign(uiText.en,{navAcademy:"5. Academy",academyTitle:"Academy",academyIntro:"Learn textbook content and reinforce it with image quizzes and practical tests.",courseProgress:"Course progress",academyLearn:"Learn",academyQuiz:"Quiz",academyPractice:"Practical test",academyProgress:"Progress",urinaryCourse:"Urinary Reflexology",urinaryCourseIntro:"Learn the locations and sequence for kidney, bladder, and adrenal reflex areas.",quizTitle:"Find the reflex area",practiceTitle:"Urinary practical test"});
Object.assign(uiText.ko,{minus10:"−10초",plus10:"+10초",timeSettings:"시간 설정",timerTitle:"포인트 적용 시간 설정",timerHelp:"1초부터 10분까지 설정할 수 있습니다. 사용 목적과 반응에 맞춰 편안한 범위에서 조정하세요.",minutes:"분",secondsLabel:"초",setTime:"설정 시간",currentOnly:"현재 포인트에만 적용",remainingAll:"남은 모든 포인트에 적용"});
Object.assign(uiText.en,{minus10:"−10 sec",plus10:"+10 sec",timeSettings:"Set time",timerTitle:"Set point duration",timerHelp:"Set from 1 second to 10 minutes. Adjust within a comfortable range for the intended use and response.",minutes:"min",secondsLabel:"sec",setTime:"Set time",currentOnly:"Apply to current point",remainingAll:"Apply to all remaining points"});
const tr=key=>uiText[state.lang][key]||uiText.ko[key]||key;
const pointLabel=point=>state.lang==="en"?(pointNamesEn[point]||point):point;
let audioContext=null;
function updateAccessButtons(){$("#langToggle").textContent=state.lang==="ko"?"EN":"한국어";$("#voiceToggle").textContent=state.voice?tr("voiceOn"):tr("voiceOff");$("#soundToggle").textContent=state.sound?tr("soundOn"):tr("soundOff");$("#voiceToggle").classList.toggle("active",state.voice);$("#soundToggle").classList.toggle("active",state.sound)}
function speak(text){if(!state.voice||!("speechSynthesis" in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=state.lang==="en"?"en-US":"ko-KR";u.rate=.92;window.speechSynthesis.speak(u)}
function speakCurrentPoint(){if(!state.activeProgram)return;speak(`${state.step+1}. ${pointLabel(state.activeProgram.points[state.step])}`)}
function playNotice(type="start"){if(!state.sound)return;const C=window.AudioContext||window.webkitAudioContext;if(!C)return;audioContext=audioContext||new C();if(audioContext.state==="suspended")audioContext.resume();const notes=type==="complete"?[660,880]:[620];notes.forEach((hz,i)=>{const o=audioContext.createOscillator(),g=audioContext.createGain(),at=audioContext.currentTime+i*.16;o.frequency.value=hz;o.type="sine";g.gain.setValueAtTime(.0001,at);g.gain.exponentialRampToValueAtTime(.12,at+.02);g.gain.exponentialRampToValueAtTime(.0001,at+.14);o.connect(g).connect(audioContext.destination);o.start(at);o.stop(at+.15)})}
function applyLanguage(){document.documentElement.lang=state.lang==="en"?"en":"ko";$$('[data-i18n]').forEach(el=>el.textContent=tr(el.dataset.i18n));updateAccessButtons();renderMaps();renderMapWorkspace();renderPrograms($("#programSearch").value);renderRecords();renderAcademy();if(state.activeProgram)renderSession();else renderTimer()}
function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),1800)}
function load(){try{const saved=JSON.parse(localStorage.getItem(key)||"{}");state.points=Array.isArray(saved.points)?saved.points:[];state.records=Array.isArray(saved.records)?saved.records:[];state.academy=saved.academy&&typeof saved.academy==="object"?{...state.academy,...saved.academy}:state.academy;state.academyCourse=saved.academyCourse||"urinary";state.mode=saved.mode||"self";state.lang=saved.lang||"ko";state.voice=saved.voice!==false;state.sound=saved.sound!==false;state.defaultDuration=clampDuration(saved.defaultDuration||20);state.time=state.defaultDuration}catch{toast("저장 자료를 읽지 못했습니다.")}}
function save(){localStorage.setItem(key,JSON.stringify({version:4,savedAt:new Date().toISOString(),mode:state.mode,lang:state.lang,voice:state.voice,sound:state.sound,defaultDuration:state.defaultDuration,points:state.points,records:state.records,academy:state.academy,academyCourse:state.academyCourse}));$("#saveStatus").textContent=state.lang==="en"?"Saved":"자동 저장 완료"}
function setView(view){state.view=view;document.body.classList.toggle("session-mode",view==="session");$$('[data-view]').forEach(b=>b.classList.toggle("active",b.dataset.view===view));$$('.view').forEach(v=>v.classList.remove("active"));$(`#${view}View`).classList.add("active");if(view==="records")renderRecords();if(view==="academy")renderAcademy();window.scrollTo({top:0,behavior:"smooth"})}
function renderMaps(){
 $("#mapButtons").innerHTML=maps.map((m,i)=>`<button class="map-button ${m.id===state.mapId?"active":""}" data-map="${m.id}"><i>${m.icon}</i><span><b>${state.lang==="en"?m.en:m.title}</b><small>${state.lang==="en"?m.title:m.en}</small></span></button>`).join("");
 $$('[data-map]').forEach(b=>b.onclick=()=>{state.mapId=b.dataset.map;state.zoom=1;state.panX=state.panY=0;state.selectedPoint=null;renderMaps();renderMapWorkspace()});
 const index=maps.findIndex(m=>m.id===state.mapId);$("#mapCount").textContent=`${String(index+1).padStart(2,"0")} / 08`;
}
function renderMapWorkspace(){const m=maps.find(x=>x.id===state.mapId);$("#mapSide").textContent=m.side;$("#mapTitle").textContent=state.lang==="en"?m.en:m.title;$("#mapSource").textContent=state.lang==="en"?`Textbook p.${m.page} · Base map protected`:`교재 ${m.page}쪽 · 기본 지도 보호`;$("#mapImage").src=`./assets/${m.image}`;$("#mapImage").alt=state.lang==="en"?`${m.en} textbook reflex map`:`${m.title} 교재 반사 지도`;applyTransform();renderCustomPoints()}
function applyTransform(){$("#mapCanvas").style.transform=`translate(${state.panX}px,${state.panY}px) scale(${state.zoom})`;$("#zoomValue").textContent=`${Math.round(state.zoom*100)}%`}
function mapPoints(){return state.points.filter(p=>p.mapId===state.mapId)}
function renderCustomPoints(){const list=mapPoints();$("#pointCount").textContent=`${list.length}개 추가점`;$("#customLayer").innerHTML=list.map((p,i)=>`<button class="custom-point ${p.id===state.selectedPoint?"selected":""}" style="left:${p.x}%;top:${p.y}%" data-point="${p.id}" title="${p.name}">${i+1}</button>`).join("");
 $$('[data-point]').forEach(el=>{el.onclick=e=>{e.stopPropagation();selectPoint(el.dataset.point)};makePointDraggable(el)});
 $("#customPointList").innerHTML=list.length?list.map(p=>`<div class="custom-item"><button data-select="${p.id}" style="color:inherit;text-align:left"><strong>${p.name}</strong><small>${p.memo||"메모 없음"}</small></button><button data-delete="${p.id}" aria-label="삭제">×</button></div>`).join(""):`<p style="color:var(--muted);font-size:.82rem">아직 추가한 포인트가 없습니다.</p>`;
 $$('[data-select]').forEach(b=>b.onclick=()=>selectPoint(b.dataset.select));$$('[data-delete]').forEach(b=>b.onclick=()=>deletePoint(b.dataset.delete));
}
function selectPoint(id){state.selectedPoint=id;const p=state.points.find(x=>x.id===id);$("#pointDetail").classList.remove("empty");$("#pointDetail").innerHTML=`<strong>${p.name}</strong><p>${p.memo||"메모가 없습니다."}</p><small>위치 X ${p.x.toFixed(1)}% · Y ${p.y.toFixed(1)}% · 사용자 추가점</small>`;renderCustomPoints()}
function deletePoint(id){if(state.mode!=="pro"){toast("전문가 모드에서만 삭제할 수 있습니다.");return}state.points=state.points.filter(p=>p.id!==id);state.selectedPoint=null;save();renderCustomPoints();toast("사용자 포인트를 삭제했습니다.")}
function makePointDraggable(el){let active=false;el.onpointerdown=e=>{if(state.mode!=="pro")return;active=true;el.setPointerCapture?.(e.pointerId);e.stopPropagation()};el.onpointermove=e=>{if(!active)return;const rect=$("#mapCanvas").getBoundingClientRect();const p=state.points.find(x=>x.id===el.dataset.point);p.x=Math.max(0,Math.min(100,(e.clientX-rect.left)/rect.width*100));p.y=Math.max(0,Math.min(100,(e.clientY-rect.top)/rect.height*100));el.style.left=`${p.x}%`;el.style.top=`${p.y}%`};el.onpointerup=()=>{if(active){active=false;save();renderCustomPoints()}}}
function setZoom(next){state.zoom=Math.max(1,Math.min(2.2,next));applyTransform()}
function setupMapPan(){const stage=$("#mapStage");let start=null;stage.onpointerdown=e=>{if(e.target.closest(".custom-point"))return;if(state.pendingPoint){placePoint(e);return}start={x:e.clientX,y:e.clientY,px:state.panX,py:state.panY};stage.setPointerCapture?.(e.pointerId);stage.classList.add("dragging")};stage.onpointermove=e=>{if(!start)return;state.panX=start.px+e.clientX-start.x;state.panY=start.py+e.clientY-start.y;applyTransform()};stage.onpointerup=()=>{start=null;stage.classList.remove("dragging")};stage.onwheel=e=>{e.preventDefault();setZoom(state.zoom+(e.deltaY<0?.1:-.1))}}
function placePoint(e){const rect=$("#mapCanvas").getBoundingClientRect();state.points.push({id:`p_${Date.now()}`,mapId:state.mapId,name:state.pendingPoint.name,memo:state.pendingPoint.memo,x:Math.max(0,Math.min(100,(e.clientX-rect.left)/rect.width*100)),y:Math.max(0,Math.min(100,(e.clientY-rect.top)/rect.height*100))});state.pendingPoint=null;$("#mapStage").style.cursor="grab";save();renderCustomPoints();toast("사용자 포인트를 추가했습니다.")}
function programCard(p){const sys=systems.find(s=>s.id===p.systemId),en=state.lang==="en";return `<article class="program-card"><div class="program-heading"><span class="program-icon">${sys.icon}</span><div><small>${en?sys.en:p.system} · ${en?`Textbook p.${p.page}`:`교재 ${p.page}쪽`}</small><h3>${en?p.en:p.title}</h3><em>${en?p.title:p.en}</em></div></div><p>${en?"Follow the numbered textbook reflex areas in order.":p.summary}</p><div class="program-preview point-only-preview" aria-label="${en?"Numbered treatment-point maps":"작업 순서에 해당하는 번호 표시 지도"}"><figure><img src="./assets/${p.footMap}" alt="${en?p.en:p.title}"><figcaption>${tr("footMap")}</figcaption></figure><figure><img src="./assets/${p.handMap}" alt="${en?p.en:p.title}"><figcaption>${tr("handMap")}</figcaption></figure></div><div class="program-points">${p.points.map((x,i)=>`<span>${i+1}. ${pointLabel(x)}</span>`).join("")}</div><button class="primary" data-start="${p.id}">${en?"Start guided session":"작업점 지도로 세션 시작"}</button></article>`}
function renderPrograms(query=""){const q=query.trim().toLowerCase(),en=state.lang==="en",grid=$("#systemGrid"),head=$("#subcategoryHead"),list=$("#programGrid"),matches=programs.filter(p=>`${p.system} ${p.title} ${p.en} ${p.summary} ${p.points.join(" ")} ${p.points.map(x=>pointNamesEn[x]||"").join(" ")}`.toLowerCase().includes(q));if(q){state.selectedSystem=null;grid.hidden=true;head.hidden=false;$("#subcategoryEyebrow").textContent="SEARCH RESULTS";$("#subcategoryTitle").textContent=en?`${matches.length} results`:`검색 결과 ${matches.length}개`;$("#subcategorySummary").textContent=en?"Results from systems, programs, and treatment points.":"계통명·소분류·작업 포인트에서 찾은 결과입니다.";list.innerHTML=matches.map(programCard).join("")||`<p class="empty-result">${en?"No results found.":"검색 결과가 없습니다."}</p>`}else if(state.selectedSystem){const sys=systems.find(s=>s.id===state.selectedSystem);grid.hidden=true;head.hidden=false;$("#subcategoryEyebrow").textContent=`${sys.no} · ${sys.en.toUpperCase()}`;$("#subcategoryTitle").textContent=en?`${sys.en} · ${sys.count} programs`:`${sys.title} 소분류 ${sys.count}개`;$("#subcategorySummary").textContent=en?"Textbook-based reflex therapy programs.":sys.summary;list.innerHTML=programs.filter(p=>p.systemId===sys.id).map(programCard).join("")}else{grid.hidden=false;head.hidden=true;list.innerHTML="";grid.innerHTML=systems.map(s=>`<button class="system-card" data-system="${s.id}"><span class="system-no">${s.no}</span><figure class="system-image"><img src="./assets/${s.image}" alt="${en?s.en:s.title} ${en?"anatomy":"해부학 이미지"}" loading="lazy"></figure><div class="system-card-copy"><i>${s.icon}</i><strong>${en?s.en:s.title}</strong><small>${en?s.title:s.en}</small><p>${en?"Textbook-based system programs":s.summary}</p><b>${en?`${s.count} programs →`:`${s.count}개 소분류 →`}</b></div></button>`).join("")}$$('[data-system]').forEach(b=>b.onclick=()=>{state.selectedSystem=b.dataset.system;renderPrograms();window.scrollTo({top:$("#programsView").offsetTop-80,behavior:"smooth"})});$$('[data-start]').forEach(b=>b.onclick=()=>startProgram(b.dataset.start))}
function clampDuration(value){return Math.max(1,Math.min(600,Math.round(Number(value)||1)))}
function pointDuration(index=state.step){return clampDuration(state.sessionDurations[index]||state.defaultDuration)}
function durationLabel(value){const m=Math.floor(value/60),s=value%60;return `${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`}
function syncTimerSettings(value=pointDuration()){const total=clampDuration(value);$("#timerMinutes").value=Math.floor(total/60);$("#timerSeconds").value=total%60;$("#timerSettingPreview").textContent=durationLabel(total);$$('[data-timer-preset]').forEach(b=>b.classList.toggle("active",Number(b.dataset.timerPreset)===total))}
function timerInputValue(){const minutes=Math.max(0,Math.min(10,Number($("#timerMinutes").value)||0)),seconds=Math.max(0,Math.min(59,Number($("#timerSeconds").value)||0));return clampDuration(minutes*60+seconds)}
function openTimerSettings(){if(!state.activeProgram){toast(tr("chooseProgram"));setView("programs");return}syncTimerSettings(state.time||pointDuration());$("#timerSettingsDialog").showModal()}
function applyDuration(scope){const total=timerInputValue();state.defaultDuration=total;if(scope==="remaining"){for(let i=state.step;i<state.sessionDurations.length;i++)state.sessionDurations[i]=total}else state.sessionDurations[state.step]=total;state.time=total;clearInterval(state.timer);state.timer=null;save();renderSession();$("#timerSettingsDialog").close();toast(state.lang==="en"?(scope==="remaining"?`Remaining points set to ${durationLabel(total)}.`:`Current point set to ${durationLabel(total)}.`):(scope==="remaining"?`남은 포인트를 ${durationLabel(total)}로 설정했습니다.`:`현재 포인트를 ${durationLabel(total)}로 설정했습니다.`))}
function adjustCurrentDuration(delta){if(!state.activeProgram){toast(tr("chooseProgram"));return}const total=clampDuration(state.time+delta);state.sessionDurations[state.step]=total;state.time=total;clearInterval(state.timer);state.timer=null;renderSession();toast(state.lang==="en"?`Current point ${durationLabel(total)}`:`현재 포인트 ${durationLabel(total)}`)}
function startProgram(id){state.activeProgram=programs.find(p=>p.id===id);state.sessionMap="foot";resetSessionMap();state.step=0;state.sessionDurations=state.activeProgram.points.map(()=>state.defaultDuration);state.time=pointDuration(0);clearInterval(state.timer);state.timer=null;renderSession();setView("session");syncTimerSettings(state.time);$("#timerSettingsDialog").showModal();speakCurrentPoint()}
function applySessionMapTransform(){const canvas=$("#sessionMapCanvas");canvas.style.transform=state.sessionFit?"none":`translate(${state.sessionPanX}px,${state.sessionPanY}px) scale(${state.sessionZoom})`;$("#sessionZoomValue").textContent=state.sessionFit?tr("full"):`${Math.round(state.sessionZoom*100)}%`}
function resetSessionMap(){state.sessionFit=true;state.sessionZoom=1;state.sessionPanX=0;state.sessionPanY=0;applySessionMapTransform()}
function setSessionZoom(next){state.sessionFit=false;state.sessionZoom=Math.max(.6,Math.min(3,next));if(state.sessionZoom<=1){state.sessionPanX=0;state.sessionPanY=0}applySessionMapTransform()}
function renderSessionMap(){const p=state.activeProgram;if(!p)return;const isFoot=state.sessionMap==="foot",label=isFoot?tr("footWork"):tr("handWork"),title=state.lang==="en"?p.en:p.title,image=$("#sessionMapImage");image.onload=()=>{if(state.sessionFit)applySessionMapTransform()};image.src=`./assets/${isFoot?p.footMap:p.handMap}`;image.alt=`${title} ${label}`;$("#sessionMapTitle").textContent=`${title} · ${label}`;$("#sessionActivePoint").textContent=`${tr("current")} ${state.step+1}. ${pointLabel(p.points[state.step])}`;$("#sessionMapCaption").textContent=state.lang==="en"?"Fit all shows the complete upper and lower maps. Zoom, then drag with a mouse or finger.":"전체 보기에서는 위·아래 지도가 모두 표시됩니다. 확대 후 마우스·손가락으로 이동할 수 있습니다.";$$('[data-session-map]').forEach(b=>b.classList.toggle("active",b.dataset.sessionMap===state.sessionMap));applySessionMapTransform()}
function setupSessionMapPan(){const frame=$("#sessionMapFrame");let start=null;frame.onpointerdown=e=>{start={x:e.clientX,y:e.clientY,px:state.sessionPanX,py:state.sessionPanY};frame.setPointerCapture?.(e.pointerId);frame.classList.add("dragging")};frame.onpointermove=e=>{if(!start)return;state.sessionFit=false;state.sessionPanX=start.px+e.clientX-start.x;state.sessionPanY=start.py+e.clientY-start.y;applySessionMapTransform()};frame.onpointerup=frame.onpointercancel=()=>{start=null;frame.classList.remove("dragging")};frame.onwheel=e=>{e.preventDefault();setSessionZoom(state.sessionZoom+(e.deltaY<0?.15:-.15))}}
function pointMethod(point,p){if(state.lang==="en")return p.id==="urinary-foot"?"Move slowly along the mapped path with thumb walking.":"Use gentle thumb walking or small circular pressure on the numbered area.";if(p.id==="reproductive-basic")return "엄지 걷기 후 발목·손목의 민감한 부위는 가운데손가락으로 가볍게 누르거나 작게 회전합니다.";if(p.id==="urinary-foot")return "지도 경로를 따라 엄지 걷기로 천천히 진행합니다.";if(["횡격막","식도","상행결장","횡행결장","하행결장","S자 결장","척추 전체","경추","흉추","요추","허리","등 상부","폐","림프","상부 림프","상부 림프계","나팔관"].includes(point))return "번호로 표시된 선이나 영역을 따라 엄지 걷기로 천천히 이동합니다.";return "번호 표시점을 엄지로 천천히 누른 뒤 작은 원을 그리듯 부드럽게 회전합니다."}
function pointSide(point,p){if(p.id==="stroke-epilepsy")return state.lang==="en"?"CP/epilepsy: both feet · Stroke: opposite foot":"뇌성마비·간질: 양발 / 뇌졸중: 마비 반대쪽 발";if(state.lang==="en"){const side=(pointGuides[point]||{}).side;return side==="왼쪽 중심"?"Mainly left":side==="오른쪽 중심"?"Mainly right":tr("both")}return (pointGuides[point]||{}).side||"양쪽"}
function renderSession(){const p=state.activeProgram;if(!p)return;const en=state.lang==="en",title=en?p.en:p.title;$("#sessionTitle").textContent=title;$("#sessionSummary").textContent=en?"Use comfortable pressure. Urgent symptoms require medical care first.":p.caution||p.summary;$("#sequenceList").innerHTML=p.points.map((x,i)=>`<li class="${i===state.step?"active":""}">${i+1}. ${pointLabel(x)} <small>${durationLabel(pointDuration(i))}</small></li>`).join("");const current=p.points[state.step],guide=pointGuides[current]||{location:"현재 번호 지도에 표시된 영역"},light=p.id==="osteoarthritis"||p.id==="reproductive-basic",intensity=light?tr("veryLight"):tr("gentle"),repeat=p.id==="facial-palsy"?tr("frequent"):tr("repeat"),location=en?`Check point ${state.step+1} on the selected hand or foot map.`:`${guide.location} · 지도 ${state.step+1}번을 함께 확인하세요.`,expert=state.mode==="pro"?`<p class="step-method"><b>${tr("method")}</b> ${pointMethod(current,p)}</p>`:"";$("#currentStep").innerHTML=`<span>STEP ${state.step+1} · ${tr("page")} ${p.page}</span><strong>${state.step+1}. ${pointLabel(current)}</strong><div class="step-meta"><i>${pointSide(current,p)}</i><i>${intensity}</i><i>${durationLabel(pointDuration())}</i><i>${repeat}</i></div><p class="step-location"><b>${tr("location")}</b> ${location}</p>${expert}`;$("#stepCounter").textContent=`${state.step+1} / ${p.points.length}`;$("#progressBar").style.width=`${(state.step+1)/p.points.length*100}%`;renderSessionMap();renderTimer()}
function renderTimer(){const m=Math.floor(state.time/60),s=state.time%60;$("#timerDisplay").textContent=`${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`;$("#timerToggle").textContent=state.timer?tr("pause"):state.time===0?tr("restart"):tr("start")}
function toggleTimer(){if(!state.activeProgram){toast(tr("chooseProgram"));setView("programs");return}if(state.timer){clearInterval(state.timer);state.timer=null;renderTimer();return}if(state.time===0)state.time=pointDuration();playNotice("start");state.timer=setInterval(()=>{state.time--;renderTimer();if(state.time<=0){clearInterval(state.timer);state.timer=null;renderTimer();playNotice("complete");toast(tr("completed"));speak(tr("completed"))}},1000);renderTimer()}
function nextStep(){if(!state.activeProgram)return;if(state.step<state.activeProgram.points.length-1){state.step++;state.time=pointDuration();clearInterval(state.timer);state.timer=null;renderSession();speakCurrentPoint()}else toast(tr("last"))}
function finishSession(){if(!state.activeProgram){toast(state.lang==="en"?"No active session.":"진행 중인 세션이 없습니다.");return}const durations=state.sessionDurations.map(clampDuration);state.records.unshift({id:Date.now(),date:new Date().toISOString(),program:state.activeProgram.title,programEn:state.activeProgram.en,steps:state.activeProgram.points.length,durations,totalSeconds:durations.reduce((a,b)=>a+b,0)});save();playNotice("complete");toast(tr("sessionSaved"));setView("records")}
function renderRecords(){const en=state.lang==="en";$("#recordCount").textContent=en?`${state.records.length} sessions`:`${state.records.length}회`;$("#recordList").innerHTML=state.records.length?state.records.map(r=>`<div class="record-item"><div><strong>${en?(r.programEn||r.program):r.program}</strong><small>${new Date(r.date).toLocaleString(en?"en-US":"ko-KR")}${r.totalSeconds?` · ${en?"Planned":"설정"} ${durationLabel(r.totalSeconds)}`:""}</small></div><span>${r.steps} ${en?"points":"포인트"}</span></div>`).join(""):`<p style="color:var(--muted)">${en?"No treatment records yet.":"아직 저장된 치료 기록이 없습니다."}</p>`}
function exportData(){const blob=new Blob([JSON.stringify({app:"NovaCell Reflex Therapy APP",version:3,exportedAt:new Date().toISOString(),points:state.points,records:state.records,academy:state.academy,academyCourse:state.academyCourse},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`NovaCell_Reflex_Backup_${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast("백업 파일을 저장했습니다.")}
function importData(file){const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(!Array.isArray(data.points)||!Array.isArray(data.records))throw Error();state.points=data.points;state.records=data.records;if(data.academy)state.academy={...state.academy,...data.academy};if(data.academyCourse&&academyCourses[data.academyCourse])state.academyCourse=data.academyCourse;save();renderMaps();renderMapWorkspace();renderRecords();renderAcademy();toast("백업을 복원했습니다.")}catch{toast("올바른 백업 파일이 아닙니다.")}};reader.readAsText(file)}

const academyCourses={
 urinary:{no:"08",titleKo:"비뇨계 반사요법",titleEn:"Urinary Reflexology",introKo:"신장·방광·부신 반사구의 위치와 작업 순서를 학습합니다.",introEn:"Learn the locations and sequence for kidney, bladder, and adrenal reflex areas.",sequenceKo:"방광 → 신장 → 부신",sequenceEn:"bladder → kidney → adrenal",lessons:[
  {ko:"과정 안내",en:"Course overview",page:"90–91",image:"p90-feet.webp",titleKo:"비뇨계 반사요법의 핵심",titleEn:"Urinary reflexology essentials",bodyKo:"방광, 신장, 부신 반사구를 배우고 그림에서 직접 찾습니다. 번호는 작업 순서를 나타냅니다.",bodyEn:"Learn the bladder, kidney, and adrenal reflex areas and find them directly on the image."},
  {ko:"1. 방광 반사구",en:"1. Bladder area",page:"90",image:"p90-feet.webp",titleKo:"① 방광 반사구",titleEn:"① Bladder reflex area",bodyKo:"발바닥 그림의 뒤꿈치 안쪽 가까이에 표시된 ①번 영역입니다.",bodyEn:"Area ① near the inner heel on the sole."},
  {ko:"2. 신장 반사구",en:"2. Kidney area",page:"90",image:"p90-feet.webp",titleKo:"② 신장 반사구",titleEn:"② Kidney reflex area",bodyKo:"발바닥 중앙보다 약간 위쪽에 표시된 ②번 영역입니다.",bodyEn:"Area ② slightly above the center of the sole."},
  {ko:"3. 부신·안전",en:"3. Adrenal & safety",page:"91",image:"p91-feet.webp",titleKo:"① 부신 반사구와 안전",titleEn:"① Adrenal area and safety",bodyKo:"발열, 혈뇨, 심한 옆구리 통증은 반사요법보다 의료기관 진료가 우선입니다.",bodyEn:"Fever, blood in urine, or severe flank pain requires medical care first."}],quiz:[
  {type:"image",questionKo:"신장 반사구 ②번을 그림에서 직접 누르세요.",questionEn:"Tap kidney reflex area ②.",image:"p90-feet.webp",target:"kidney"},
  {type:"choice",questionKo:"뒤꿈치 안쪽 가까이에 있는 ①번 반사구의 명칭은 무엇입니까?",questionEn:"What is area ① near the inner heel?",optionsKo:["방광","신장","부신"],optionsEn:["Bladder","Kidney","Adrenal"],answer:0},
  {type:"choice",questionKo:"발열·혈뇨·심한 옆구리 통증이 있을 때 가장 먼저 해야 할 일은 무엇입니까?",questionEn:"What comes first with acute urinary symptoms?",optionsKo:["강하게 자극하기","의료기관 진료 받기","오랫동안 마사지하기"],optionsEn:["Strong pressure","Seek medical care","Massage longer"],answer:1}],practice:[
  {nameKo:"방광 반사구",nameEn:"Bladder area",image:"p90-feet.webp",target:"bladder",score:40},{nameKo:"신장 반사구",nameEn:"Kidney area",image:"p90-feet.webp",target:"kidney",score:35},{nameKo:"부신 반사구",nameEn:"Adrenal area",image:"p91-feet.webp",target:"adrenal",score:25}]},
 cardio:{no:"01",titleKo:"심혈관계 반사요법",titleEn:"Cardiovascular Reflexology",introKo:"뇌간·부신·횡격막·심장 반사구와 5개 교재 프로그램을 학습합니다.",introEn:"Learn brainstem, adrenal, diaphragm, and heart reflex areas with five textbook programs.",sequenceKo:"뇌간 → 부신 → 횡격막 → 심장",sequenceEn:"brainstem → adrenal → diaphragm → heart",lessons:[
  {ko:"과정 안내",en:"Course overview",page:"48–52",image:"p48-feet.webp",titleKo:"심혈관계 5개 프로그램",titleEn:"Five cardiovascular programs",bodyKo:"심혈관계 발 반사요법, 부정맥·울혈성 심부전, 고혈압, 심장마비, 저혈압 프로그램을 교재 그림과 함께 학습합니다.",bodyEn:"Study foot reflexology, arrhythmia/heart failure, hypertension, heart attack, and hypotension programs."},
  {ko:"1. 뇌간 반사구",en:"1. Brainstem area",page:"48",image:"p48-feet.webp",titleKo:"① 뇌간 반사구",titleEn:"① Brainstem reflex area",bodyKo:"양쪽 엄지발가락 안쪽에 표시된 ①번 영역을 확인합니다.",bodyEn:"Find area ① on the inner side of both big toes."},
  {ko:"2. 부신 반사구",en:"2. Adrenal area",page:"48",image:"p48-feet.webp",titleKo:"② 부신 반사구",titleEn:"② Adrenal reflex area",bodyKo:"발바닥 중앙의 안쪽 부근에 표시된 ②번 영역입니다.",bodyEn:"Find area ② near the inner middle of the sole."},
  {ko:"3. 횡격막 반사구",en:"3. Diaphragm area",page:"48",image:"p48-feet.webp",titleKo:"③ 횡격막 반사구",titleEn:"③ Diaphragm reflex area",bodyKo:"앞발과 중간발 사이를 가로지르는 ③번 선을 확인합니다.",bodyEn:"Find line ③ crossing between the forefoot and midfoot."},
  {ko:"4. 심장·안전",en:"4. Heart & safety",page:"48",image:"p48-hands.webp",titleKo:"④ 심장 반사구와 안전",titleEn:"④ Heart area and safety",bodyKo:"④번 심장 반사구를 확인합니다. 갑작스러운 흉통, 호흡곤란, 식은땀, 의식 변화는 즉시 응급진료가 우선입니다.",bodyEn:"Find heart area ④. Sudden chest pain, breathing difficulty, cold sweat, or altered consciousness requires emergency care."}],quiz:[
  {type:"image",questionKo:"심장 반사구 ④번을 발 그림에서 직접 누르세요.",questionEn:"Tap heart reflex area ④ on the foot image.",image:"p48-feet.webp",target:"heart"},
  {type:"choice",questionKo:"심혈관계 기본 작업 순서로 알맞은 것은 무엇입니까?",questionEn:"Which is the correct basic sequence?",optionsKo:["뇌간 → 부신 → 횡격막 → 심장","심장 → 뇌간 → 부신 → 횡격막","부신 → 심장 → 뇌간 → 횡격막"],optionsEn:["Brainstem → adrenal → diaphragm → heart","Heart → brainstem → adrenal → diaphragm","Adrenal → heart → brainstem → diaphragm"],answer:0},
  {type:"choice",questionKo:"갑작스러운 흉통과 호흡곤란이 생기면 무엇이 우선입니까?",questionEn:"What comes first with sudden chest pain and breathing difficulty?",optionsKo:["반사구를 강하게 누르기","즉시 응급진료 받기","30분간 계속 자극하기"],optionsEn:["Press strongly","Seek emergency care","Continue for 30 minutes"],answer:1}],practice:[
  {nameKo:"뇌간 반사구",nameEn:"Brainstem area",image:"p48-feet.webp",target:"brainstem",score:25},{nameKo:"부신 반사구",nameEn:"Adrenal area",image:"p48-feet.webp",target:"cardioAdrenal",score:25},{nameKo:"횡격막 반사구",nameEn:"Diaphragm area",image:"p48-feet.webp",target:"diaphragm",score:25},{nameKo:"심장 반사구",nameEn:"Heart area",image:"p48-feet.webp",target:"heart",score:25}]}
};
function academyText(ko,en){return state.lang==="en"?en:ko}
function ensureAcademyState(){if(!state.academy.courses){const old={lessons:state.academy.lessons||[],quizBest:state.academy.quizBest||0,practiceBest:state.academy.practiceBest||0,attempts:state.academy.attempts||0};state.academy={courses:{urinary:old,cardio:{lessons:[],quizBest:0,practiceBest:0,attempts:0}}}}Object.keys(academyCourses).forEach(id=>state.academy.courses[id]??={lessons:[],quizBest:0,practiceBest:0,attempts:0})}
function currentAcademyCourse(){return academyCourses[state.academyCourse]||academyCourses.urinary}
function currentAcademyProgress(){ensureAcademyState();return state.academy.courses[state.academyCourse]}
function academyStats(){const c=currentAcademyCourse(),p=currentAcademyProgress(),learned=new Set(p.lessons||[]).size,progress=Math.round((learned/c.lessons.length)*60+(p.quizBest>0?20:0)+(p.practiceBest>0?20:0));return{learned,progress:Math.min(100,progress)}}
function renderAcademy(){if(!$("#academyView"))return;ensureAcademyState();const c=currentAcademyCourse(),p=currentAcademyProgress(),stats=academyStats();$("#academyCoursePicker").innerHTML=Object.entries(academyCourses).map(([id,x])=>`<button class="${id===state.academyCourse?"active":""}" data-academy-course="${id}"><span>${x.no}</span><strong>${academyText(x.titleKo,x.titleEn)}</strong><small>${academyStatsFor(id)}%</small></button>`).join("");$$('[data-academy-course]').forEach(b=>b.onclick=()=>switchAcademyCourse(b.dataset.academyCourse));$("#academyCourseTitle").textContent=academyText(c.titleKo,c.titleEn);$("#academyCourseIntro").textContent=academyText(c.introKo,c.introEn);$("#academyProgressText").textContent=`${stats.progress}%`;$("#academyProgressBar").style.width=`${stats.progress}%`;$("#academyBestScore").textContent=academyText(`퀴즈 ${p.quizBest}점 · 실기 ${p.practiceBest}점`,`Quiz ${p.quizBest} · Practical ${p.practiceBest}`);$('[data-i18n="practiceTitle"]').textContent=academyText(`${c.titleKo} 실기평가`,`${c.titleEn} practical test`);renderLessonList();renderLesson();renderQuiz();renderPractice();renderAcademyDashboard()}
function academyStatsFor(id){const previous=state.academyCourse;state.academyCourse=id;const value=academyStats().progress;state.academyCourse=previous;return value}
function switchAcademyCourse(id){clearInterval(state.practiceTimer);state.practiceTimer=null;state.academyCourse=id;state.lesson=0;state.quiz=0;state.quizScore=0;state.practiceActive=false;state.practiceTime=60;state.practiceStep=0;state.practiceScore=0;save();renderAcademy();toast(academyText(`${academyCourses[id].titleKo} 과정`,`${academyCourses[id].titleEn} course`))}
function renderLessonList(){const c=currentAcademyCourse(),p=currentAcademyProgress();$("#lessonList").innerHTML=c.lessons.map((l,i)=>`<li><button class="${i===state.lesson?"active":""}" data-lesson="${i}"><span>${p.lessons.includes(i)?"✓":String(i+1).padStart(2,"0")}</span><b>${academyText(l.ko,l.en)}</b><small>p.${l.page}</small></button></li>`).join("");$$('[data-lesson]').forEach(b=>b.onclick=()=>{state.lesson=Number(b.dataset.lesson);renderLessonList();renderLesson()})}
function renderLesson(){const c=currentAcademyCourse(),p=currentAcademyProgress(),l=c.lessons[state.lesson];$("#lessonStage").innerHTML=`<div class="lesson-copy"><p class="eyebrow">TEXTBOOK · PAGE ${l.page}</p><h3>${academyText(l.titleKo,l.titleEn)}</h3><p>${academyText(l.bodyKo,l.bodyEn)}</p><div class="lesson-tags"><span>${academyText("양쪽 손·발 비교","Compare both hands/feet")}</span><span>${academyText("편안한 강도 3–4/10","Comfortable 3–4/10")}</span></div><button class="primary" id="completeLesson">${p.lessons.includes(state.lesson)?academyText("✓ 학습 완료","✓ Completed"):academyText("이 단원 학습 완료","Complete this lesson")}</button></div><figure class="lesson-image"><img src="./assets/reflex-split/${l.image}" alt="${academyText(l.titleKo,l.titleEn)}"><figcaption>${academyText("번호가 표시된 교재 기반 작업점 지도","Numbered textbook work-point map")}</figcaption></figure>`;$("#completeLesson").onclick=()=>{if(!p.lessons.includes(state.lesson))p.lessons.push(state.lesson);save();playNotice("complete");renderAcademy();toast(academyText("학습 진도를 저장했습니다.","Learning progress saved."))}}
function renderQuiz(){const c=currentAcademyCourse(),p=currentAcademyProgress(),q=c.quiz[state.quiz];$("#quizCounter").textContent=`${Math.min(state.quiz+1,c.quiz.length)} / ${c.quiz.length}`;if(!q){const score=Math.round(state.quizScore/c.quiz.length*100);p.quizBest=Math.max(p.quizBest,score);p.attempts++;save();$("#quizBody").innerHTML=resultCard(academyText("퀴즈 완료","Quiz complete"),score,"restartQuiz");$("#restartQuiz").onclick=()=>{state.quiz=0;state.quizScore=0;renderQuiz()};renderAcademyDashboard();return}const question=academyText(q.questionKo,q.questionEn);if(q.type==="image"){$("#quizBody").innerHTML=`<p class="assessment-question">${question}</p>${clickMap(q.image,"quizClickMap")}<p class="answer-feedback" id="quizFeedback">${academyText("그림의 위치를 직접 눌러 보세요.","Tap the location directly on the image.")}</p>`;bindMapAnswer("quizClickMap",q.target,ok=>answerQuiz(ok))}else{$("#quizBody").innerHTML=`<p class="assessment-question">${question}</p><div class="answer-options">${academyText(q.optionsKo,q.optionsEn).map((x,i)=>`<button data-quiz-answer="${i}">${x}</button>`).join("")}</div><p class="answer-feedback" id="quizFeedback"></p>`;$$('[data-quiz-answer]').forEach(b=>b.onclick=()=>answerQuiz(Number(b.dataset.quizAnswer)===q.answer,b))}}
function answerQuiz(ok,button){if(button){$$('[data-quiz-answer]').forEach(x=>x.disabled=true);button.classList.add(ok?"correct":"wrong")}const fb=$("#quizFeedback");fb.textContent=ok?academyText("정답입니다!","Correct!"):academyText("다시 확인해 보세요. 정답 위치를 표시했습니다.","Review the correct location.");fb.className=`answer-feedback ${ok?"correct":"wrong"}`;if(ok)state.quizScore++;playNotice(ok?"complete":"start");setTimeout(()=>{state.quiz++;renderQuiz()},900)}
function clickMap(image,id){return `<div class="answer-map" id="${id}"><img src="./assets/reflex-split/${image}" alt="${academyText("반사구 위치 선택 지도","Reflex area selection map")}"><i class="answer-marker" hidden></i></div>`}
function pointHit(target,x,y){const zones={kidney:[[.38,.61],[.64,.61]],bladder:[[.39,.82],[.60,.82]],adrenal:[[.38,.50],[.62,.49]],brainstem:[[.35,.06],[.59,.06]],cardioAdrenal:[[.35,.48],[.58,.48]],diaphragm:[[.25,.37],[.71,.36]],heart:[[.40,.33],[.54,.33]]};return zones[target].some(([zx,zy])=>Math.hypot(x-zx,y-zy)<.13)}
function bindMapAnswer(id,target,done){const map=$("#"+id);map.onclick=e=>{if(map.dataset.done)return;const r=map.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height,ok=pointHit(target,x,y),mark=map.querySelector("i");map.dataset.done="1";mark.hidden=false;mark.style.left=`${x*100}%`;mark.style.top=`${y*100}%`;mark.classList.add(ok?"correct":"wrong");done(ok)}}
function resultCard(title,score,id){return `<div class="result-card"><span>${score}</span><h3>${title}</h3><p>${score>=80?academyText("잘하셨습니다. 다음 단계로 진행할 수 있습니다.","Well done. You can continue to the next stage."):academyText("학습 내용을 복습한 뒤 다시 도전해 보세요.","Review the lesson and try again.")}</p><button class="primary" id="${id}">${academyText("다시 도전","Try again")}</button></div>`}
function renderPractice(){clearInterval(state.practiceTimer);state.practiceTimer=null;const c=currentAcademyCourse(),p=currentAcademyProgress(),tasks=c.practice,body=$("#practiceBody");if(state.practiceStep>=tasks.length){const score=state.practiceScore;p.practiceBest=Math.max(p.practiceBest,score);save();body.innerHTML=resultCard(academyText("실기평가 완료","Practical test complete"),score,"restartPractice");$("#practiceTimer").textContent=academyText("완료","Done");$("#restartPractice").onclick=resetPractice;renderAcademyDashboard();return}if(!state.practiceActive){body.innerHTML=`<div class="practice-start"><p>${academyText(`60초 안에 ${c.sequenceKo} 반사구를 순서대로 그림에서 찾으세요.`,`Within 60 seconds, find ${c.sequenceEn} in order.`)}</p><ul><li>${academyText("위치 정확도 100점","Location accuracy: 100 points")}</li><li>${academyText("그림을 직접 눌러 답하기","Tap the image to answer")}</li><li>${academyText("급성 증상은 의료기관 진료가 우선","Medical care first for acute symptoms")}</li></ul><button class="primary" id="startPractice">${academyText("실기평가 시작","Start practical test")}</button></div>`;$("#practiceTimer").textContent="01:00";$("#startPractice").onclick=startPractice;return}const t=tasks[state.practiceStep];body.innerHTML=`<p class="assessment-question">${state.practiceStep+1}. ${academyText(t.nameKo,t.nameEn)} — ${academyText("정확한 위치를 누르세요.","Tap the correct location.")}</p>${clickMap(t.image,"practiceClickMap")}<p class="answer-feedback" id="practiceFeedback">${academyText("남은 시간 안에 위치를 선택하세요.","Select the location before time runs out.")}</p>`;bindMapAnswer("practiceClickMap",t.target,ok=>{if(ok)state.practiceScore+=t.score;$("#practiceFeedback").textContent=ok?academyText(`정확합니다. +${t.score}점`,`Correct. +${t.score}`):academyText("위치를 다시 복습해 주세요.","Please review this location.");setTimeout(()=>{state.practiceStep++;renderPractice();if(state.practiceStep<tasks.length)startPracticeTimer()},700)})}
function startPractice(){state.practiceActive=true;state.practiceTime=60;state.practiceStep=0;state.practiceScore=0;renderPractice();startPracticeTimer()}
function startPracticeTimer(){clearInterval(state.practiceTimer);state.practiceTimer=setInterval(()=>{state.practiceTime--;const m=Math.floor(state.practiceTime/60),s=state.practiceTime%60;$("#practiceTimer").textContent=`${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`;if(state.practiceTime<=0){clearInterval(state.practiceTimer);state.practiceStep=currentAcademyCourse().practice.length;renderPractice()}},1000)}
function resetPractice(){clearInterval(state.practiceTimer);state.practiceTimer=null;state.practiceActive=false;state.practiceTime=60;state.practiceStep=0;state.practiceScore=0;renderPractice()}
function renderAcademyDashboard(){const c=currentAcademyCourse(),p=currentAcademyProgress(),s=academyStats();$("#academyDashboard").innerHTML=`<article class="progress-card panel"><span>${s.progress}%</span><h3>${academyText(c.titleKo,c.titleEn)}</h3><p>${academyText(`${c.lessons.length}개 학습 단원 중 ${s.learned}개 완료`,`${s.learned} of ${c.lessons.length} lessons complete`)}</p></article><article class="progress-card panel"><span>${p.quizBest}</span><h3>${academyText("퀴즈 최고점수","Best quiz score")}</h3><p>${academyText(`총 ${p.attempts}회 응시`,`Attempts: ${p.attempts}`)}</p></article><article class="progress-card panel"><span>${p.practiceBest}</span><h3>${academyText("실기평가 최고점수","Best practical score")}</h3><p>${academyText("위치 정확도 평가","Location accuracy assessment")}</p></article>`}
function setAcademyTab(tab){state.academyTab=tab;if(tab!=="practice"){clearInterval(state.practiceTimer);state.practiceTimer=null}$$('[data-academy-tab]').forEach(b=>b.classList.toggle("active",b.dataset.academyTab===tab));$$('.academy-panel').forEach(p=>p.classList.remove("active"));$(`#academy${tab[0].toUpperCase()+tab.slice(1)}Panel`).classList.add("active");if(tab==="progress")renderAcademyDashboard()}
function bind(){
 const closeWelcome=()=>{const gate=$("#welcomeGate");gate.classList.add("closing");document.body.classList.remove("welcome-open");setTimeout(()=>gate.hidden=true,320)};
 const openWelcome=()=>{const gate=$("#welcomeGate");gate.hidden=false;gate.classList.remove("closing");document.body.classList.add("welcome-open");gate.scrollTop=0};
 $("#welcomeStart").onclick=closeWelcome;$("#welcomeClose").onclick=closeWelcome;
 $("#homeGateBtn").onclick=openWelcome;
 $("#langToggle").onclick=()=>{state.lang=state.lang==="ko"?"en":"ko";save();applyLanguage();toast(state.lang==="en"?"English mode":"한국어 모드")};$("#voiceToggle").onclick=()=>{state.voice=!state.voice;if(!state.voice&&"speechSynthesis" in window)window.speechSynthesis.cancel();save();updateAccessButtons();if(state.voice)speak(state.lang==="en"?"Voice guidance on":"음성 안내가 켜졌습니다")};$("#soundToggle").onclick=()=>{state.sound=!state.sound;save();updateAccessButtons();if(state.sound)playNotice("start")};
 $$('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$$('[data-academy-tab]').forEach(b=>b.onclick=()=>setAcademyTab(b.dataset.academyTab));$$('[data-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;$$('[data-mode]').forEach(x=>x.classList.toggle("active",x.dataset.mode===state.mode));save();if(state.activeProgram)renderSession();toast(state.mode==="pro"?"전문가 모드: 상세 자극 방법을 표시합니다.":"자가관리 모드: 핵심 안내만 표시합니다.")});
 $("#zoomIn").onclick=()=>setZoom(state.zoom+.15);$("#zoomOut").onclick=()=>setZoom(state.zoom-.15);$("#resetMapBtn").onclick=()=>{state.zoom=1;state.panX=state.panY=0;applyTransform()};
 $("#addPointBtn").onclick=()=>{if(state.mode!=="pro"){toast("사용자 포인트는 전문가 모드에서 추가합니다.");return}$("#pointDialog").showModal()};$("#pointForm").onsubmit=e=>{e.preventDefault();state.pendingPoint={name:$("#pointName").value.trim(),memo:$("#pointMemo").value.trim()};if(!state.pendingPoint.name)return;$("#pointDialog").close();$("#mapStage").style.cursor="crosshair";toast("지도에서 위치를 선택하세요.")};
 $("#programSearch").oninput=e=>renderPrograms(e.target.value);$("#backToSystems").onclick=()=>{state.selectedSystem=null;$("#programSearch").value="";renderPrograms()};$$('[data-session-map]').forEach(b=>b.onclick=()=>{if(!state.activeProgram){toast("프로그램을 먼저 선택하세요.");setView("programs");return}state.sessionMap=b.dataset.sessionMap;resetSessionMap();renderSessionMap()});$("#sessionZoomIn").onclick=()=>setSessionZoom(state.sessionZoom+.2);$("#sessionZoomOut").onclick=()=>setSessionZoom(state.sessionZoom-.2);$("#sessionMapReset").onclick=resetSessionMap;$("#timerToggle").onclick=toggleTimer;$("#timerMinus").onclick=()=>adjustCurrentDuration(-10);$("#timerPlus").onclick=()=>adjustCurrentDuration(10);$("#openTimerSettings").onclick=openTimerSettings;$("#closeTimerSettings").onclick=()=>$("#timerSettingsDialog").close();$$('[data-timer-preset]').forEach(b=>b.onclick=()=>syncTimerSettings(Number(b.dataset.timerPreset)));$("#timerMinutes").oninput=$("#timerSeconds").oninput=()=>syncTimerSettings(timerInputValue());$("#applyCurrentTime").onclick=()=>applyDuration("current");$("#applyRemainingTime").onclick=()=>applyDuration("remaining");$("#nextStep").onclick=nextStep;$("#finishSession").onclick=finishSession;$("#exportBtn").onclick=exportData;$("#importInput").onchange=e=>e.target.files[0]&&importData(e.target.files[0]);$("#clearBtn").onclick=()=>{if(confirm("사용자 추가점과 치료 기록을 모두 지울까요?")){state.points=[];state.records=[];save();renderMapWorkspace();renderRecords();toast("사용자 데이터를 지웠습니다.")}};
 $("#safetyBtn").onclick=()=>$("#safetyDialog").showModal();$("#closeSafety").onclick=()=>$("#safetyDialog").close();$("#acceptSafety").onclick=()=>$("#safetyDialog").close();
 setupMapPan();setupSessionMapPan();
}
document.body.classList.add("welcome-open");load();bind();applyLanguage();$$('[data-mode]').forEach(b=>b.classList.toggle("active",b.dataset.mode===state.mode));
if("serviceWorker" in navigator)navigator.serviceWorker.register("./service-worker.js");
