window.CLINICAL_DICTIONARY = [
  [/대후두신경/g, 'Greater occipital nerve'],
  [/소후두신경/g, 'Lesser occipital nerve'],
  [/승모근/g, 'trapezius'],
  [/두반극근/g, 'semispinalis capitis'],
  [/두판상근/g, 'splenius capitis'],
  [/후두하삼각/g, 'suboccipital triangle'],
  [/상항선/g, 'superior nuchal line'],
  [/외후두융기/g, 'external occipital protuberance (EOP)'],
  [/유양돌기/g, 'mastoid process'],
  [/후관절/g, 'facet joint'],
  [/신경근/g, 'nerve root'],
  [/삼차신경/g, 'trigeminal nerve'],
  [/안면신경/g, 'facial nerve'],
  [/이개측두신경/g, 'auriculotemporal nerve'],
  [/안와상절제점/g, 'supraorbital notch point'],
  [/안와하공/g, 'infraorbital foramen'],
  [/이공/g, 'mental foramen'],
  [/경돌유돌공/g, 'stylomastoid foramen'],
  [/협근/g, 'buccinator'],
  [/안륜근/g, 'orbicularis oculi'],
  [/외측익돌근/g, 'lateral pterygoid'],
  [/교근/g, 'masseter'],
  [/상완이두근/g, 'biceps brachii'],
  [/극상근/g, 'supraspinatus'],
  [/극하근/g, 'infraspinatus'],
  [/소원근/g, 'teres minor'],
  [/견갑하근/g, 'subscapularis'],
  [/오훼돌기/g, 'coracoid process'],
  [/사각근/g, 'scalene muscle'],
  [/견갑배신경/g, 'dorsal scapular nerve'],
  [/능형근/g, 'rhomboid muscle'],
  [/외측상과/g, 'lateral epicondyle'],
  [/내측상과/g, 'medial epicondyle'],
  [/척골신경/g, 'ulnar nerve'],
  [/정중신경/g, 'median nerve'],
  [/수근관/g, 'carpal tunnel'],
  [/횡수근인대/g, 'transverse carpal ligament'],
  [/방아쇠수지/g, 'trigger finger'],
  [/드퀘르벵/g, 'de Quervain'],
  [/늑간신경/g, 'intercostal nerve'],
  [/흉추/g, 'thoracic spine'],
  [/요추/g, 'lumbar spine'],
  [/천장관절/g, 'sacroiliac joint'],
  [/천골/g, 'sacrum'],
  [/이상근/g, 'piriformis'],
  [/좌골신경/g, 'sciatic nerve'],
  [/총비골신경/g, 'common peroneal nerve'],
  [/비골두/g, 'fibular head'],
  [/전거비인대/g, 'anterior talofibular ligament (ATFL)'],
  [/종비인대/g, 'calcaneofibular ligament (CFL)'],
  [/족저근막/g, 'plantar fascia'],
  [/종골/g, 'calcaneus'],
  [/발목터널/g, 'tarsal tunnel'],
  [/후경골신경/g, 'posterior tibial nerve'],
  [/성상신경절/g, 'stellate ganglion'],
  [/미세전류/g, 'microcurrent'],
  [/고전압/g, 'high-voltage'],
  [/압통점/g, 'tender point'],
  [/방사통/g, 'radiating pain'],
  [/포착/g, 'entrapment'],
  [/해소/g, 'release'],
  [/도자/g, 'probe'],
  [/직각 안착/g, 'perpendicular seating'],
  [/심부/g, 'deep'],
  [/부착부/g, 'insertion/attachment'],
  [/기시부/g, 'origin'],
  [/건초염/g, 'tenosynovitis'],
  [/활액낭염/g, 'bursitis'],
  [/관절낭/g, 'joint capsule'],
  [/인대/g, 'ligament'],
  [/힘줄/g, 'tendon'],
  [/신경통/g, 'neuralgia'],
  [/마비/g, 'palsy/paralysis'],
  [/부종/g, 'edema/swelling'],
  [/허혈/g, 'ischemia'],
  [/자극/g, 'stimulation/irritation'],
  [/조직/g, 'tissue'],
  [/외측/g, 'lateral'],
  [/내측/g, 'medial'],
  [/전면/g, 'anterior'],
  [/후면/g, 'posterior'],
  [/측면/g, 'lateral view'],
  [/상방/g, 'superior'],
  [/하방/g, 'inferior'],
  [/좌우/g, 'bilateral'],
  [/환자/g, 'patient'],
  [/치료점은 직접 배치/g, 'Place points directly'],
  [/질환별 참고 해부도/g, 'Clinical anatomy reference'],
  [/후면·측면 비교/g, 'Posterior & lateral comparison'],
  [/동시 비교/g, 'dual-view comparison'],
  [/참고/g, 'reference'],
  [/극돌기/g, 'spinous process'],
  [/횡돌기/g, 'transverse process'],
  [/천골공/g, 'sacral foramen'],
  [/후상장골극/g, 'PSIS'],
  [/대퇴/g, 'femoral/thigh'],
  [/슬개골/g, 'patella'],
  [/거위발건/g, 'pes anserine tendon'],
  [/비골/g, 'fibula'],
  [/경골/g, 'tibia'],
  [/족하수/g, 'foot drop'],
  [/수부/g, 'hand'],
  [/족부/g, 'foot'],
  [/체간부/g, 'torso/trunk'],
  [/대상포진/g, 'herpes zoster'],
  [/흉곽출구/g, 'thoracic outlet'],
  [/오십견/g, 'frozen shoulder'],
  [/회전근개/g, 'rotator cuff'],
  [/테니스 엘보/g, 'tennis elbow'],
  [/골퍼 엘보/g, 'golfer\'s elbow']
];
window.translateClinicalText = function(text) {
  if (!text || typeof text !== 'string') return text;
  var res = text;
  for (var i = 0; i < window.CLINICAL_DICTIONARY.length; i++) {
    res = res.replace(window.CLINICAL_DICTIONARY[i][0], window.CLINICAL_DICTIONARY[i][1]);
  }
  return res;
};
console.log(window.translateClinicalText('대후두신경'));